# Generated by Django 5.2.9 on 2026-01-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoAlmacen',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('ubicacion_almacen', models.CharField(choices=[('AG', 'Almacen General'), ('AD', 'Almacen de deporte'), ('ID', 'Imprenta deportes')], max_length=2)),
                ('estante', models.CharField(max_length=50)),
                ('cantidad', models.PositiveIntegerField()),
                ('unidad', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('DISP', 'Disponible'), ('AGOT', 'Agotado'), ('BAJO', 'Stock Bajo')], max_length=4)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
