# Generated by Django 4.2.27 on 2026-01-26 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('abreviatura', models.CharField(blank=True, max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'db_table': 'app1_unidad',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoAlmacen',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_almacen', models.CharField(editable=False, max_length=2)),
                ('codigo_producto', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('ubicacion_almacen', models.CharField(choices=[('AG', 'Almacén General'), ('AD', 'Almacén de Deporte'), ('IU', 'Almacén de Útiles')], max_length=2)),
                ('estante', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('DISP', 'Disponible'), ('AGOT', 'Agotado'), ('BAJO', 'Stock Bajo')], default='DISP', max_length=4)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='app1.unidad')),
            ],
            options={
                'verbose_name': 'Producto de Almacén',
                'verbose_name_plural': 'Productos de Almacén',
                'db_table': 'app1_productoalmacen',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('PRESTAMO', 'Préstamo'), ('DEVOLUCION', 'Devolución'), ('AJUSTE', 'Ajuste')], max_length=10)),
                ('cantidad', models.IntegerField()),
                ('cantidad_anterior', models.PositiveIntegerField()),
                ('cantidad_nueva', models.PositiveIntegerField()),
                ('estante_anterior', models.CharField(blank=True, max_length=50, null=True)),
                ('estante_nuevo', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='app1.productoalmacen')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'db_table': 'app1_movimientoinventario',
                'ordering': ['-fecha_movimiento'],
            },
        ),
    ]
