# Generated by Django 5.2.9 on 2026-01-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('abreviatura', models.CharField(blank=True, max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'db_table': 'app1_unidad',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='productoalmacen',
            options={'verbose_name': 'Producto de Almacén', 'verbose_name_plural': 'Productos de Almacén'},
        ),
        migrations.AddField(
            model_name='productoalmacen',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productoalmacen',
            name='ubicacion_almacen',
            field=models.CharField(choices=[('AG', 'Almacén General'), ('AD', 'Almacén de Deporte'), ('ID', 'Imprenta Deportes')], max_length=2),
        ),
        migrations.AlterModelTable(
            name='productoalmacen',
            table='app1_productoalmacen',
        ),
    ]
