# Generated by Django 4.2.27 on 2026-01-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='pedidos_compra/')),
                ('estado', models.CharField(choices=[('PEND', 'Pendiente'), ('COMP', 'Completado'), ('ENTR', 'Entregado')], default='PEND', max_length=4)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pedido de Compra',
                'verbose_name_plural': 'Pedidos de Compra',
                'db_table': 'pedidos_compra',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
