# Generated by Django 4.2.27 on 2026-01-27 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_pedidocompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocompra',
            name='documento_entrega',
            field=models.FileField(blank=True, null=True, upload_to='documentos_entrega/'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id_cotizacion', models.AutoField(primary_key=True, serialize=False)),
                ('proveedor', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('documento', models.FileField(upload_to='cotizaciones/')),
                ('estado', models.CharField(choices=[('PEND', 'Pendiente'), ('SELEC', 'Seleccionada'), ('RECH', 'Rechazada')], default='PEND', max_length=5)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='app1.pedidocompra')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'db_table': 'cotizaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
