# Generated by Django 5.2.9 on 2026-01-31 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_pedidocompra_documento_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocompra',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='pedidos_compra/'),
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_solicitada', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app1.pedidocompra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_pedido', to='app1.productoalmacen')),
            ],
            options={
                'verbose_name': 'Item de Pedido',
                'verbose_name_plural': 'Items de Pedido',
                'db_table': 'items_pedido',
                'ordering': ['fecha_agregado'],
            },
        ),
    ]
