# Generated by Django 5.2.9 on 2026-02-02 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alumno_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaUtil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entregado', models.BooleanField(default=False)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='app1.alumno')),
            ],
            options={
                'verbose_name': 'Entrega de Útil',
                'verbose_name_plural': 'Entregas de Útiles',
                'ordering': ['util__orden', 'util__nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='app1.entregautil')),
            ],
            options={
                'verbose_name': 'Historial de Entrega',
                'verbose_name_plural': 'Historial de Entregas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='UtilEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField(default=1)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utiles', to='app1.salon')),
            ],
            options={
                'verbose_name': 'Útil Escolar',
                'verbose_name_plural': 'Útiles Escolares',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='entregautil',
            name='util',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='app1.utilescolar'),
        ),
        migrations.AlterUniqueTogether(
            name='entregautil',
            unique_together={('alumno', 'util')},
        ),
    ]
