# Generated by Django 4.2.27 on 2026-02-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_entregautil_historialentrega_utilescolar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregautil',
            name='cantidad_entregada',
            field=models.IntegerField(default=0),
        ),
    ]
